In [1]:
import numpy
n = numpy.arange(27)

In [2]:
n

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [4]:
n.reshape(3, 9)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [6]:
n.reshape(3, 3, 3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [9]:
a = n.reshape(3, 3, 3)[0]
b = n.reshape(3, 3, 3)[1]
c = n.reshape(3, 3, 3)[2]
d = a * 3
print(d)

[[ 0  3  6]
 [ 9 12 15]
 [18 21 24]]


In [10]:
import cv2

In [13]:
im_g = cv2.imread("100 smallgray.png", 0)
im_g

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [18]:
print(im_g[0:2, 2:4])
im_g.shape


[[104 121]
 [255 255]]


(3, 5)

In [20]:
for i in im_g.T:
    print(i)

[187 198 209]
[158 125 134]
[104 255 255]
[121 255  97]
[143 147 182]


In [23]:
for i in im_g[0:2, 2:4].T:
    print(i)

[104 255]
[121 255]


In [29]:
ims = numpy.hstack((im_g, im_g))
ems = numpy.vstack((ims, ims))
print(ims)
print(ems)

[[187 158 104 121 143 187 158 104 121 143]
 [198 125 255 255 147 198 125 255 255 147]
 [209 134 255  97 182 209 134 255  97 182]]
[[187 158 104 121 143 187 158 104 121 143]
 [198 125 255 255 147 198 125 255 255 147]
 [209 134 255  97 182 209 134 255  97 182]
 [187 158 104 121 143 187 158 104 121 143]
 [198 125 255 255 147 198 125 255 255 147]
 [209 134 255  97 182 209 134 255  97 182]]


In [32]:
lst = numpy.hsplit(ems, 5)
print(lst)


[array([[187, 158],
       [198, 125],
       [209, 134],
       [187, 158],
       [198, 125],
       [209, 134]], dtype=uint8), array([[104, 121],
       [255, 255],
       [255,  97],
       [104, 121],
       [255, 255],
       [255,  97]], dtype=uint8), array([[143, 187],
       [147, 198],
       [182, 209],
       [143, 187],
       [147, 198],
       [182, 209]], dtype=uint8), array([[158, 104],
       [125, 255],
       [134, 255],
       [158, 104],
       [125, 255],
       [134, 255]], dtype=uint8), array([[121, 143],
       [255, 147],
       [ 97, 182],
       [121, 143],
       [255, 147],
       [ 97, 182]], dtype=uint8)]
